import type { Metadata } from "next"
import { Inter, Syne } from "next/font/google"
import Header from "@/components/Header"
import "@/styles/globals.css"
import { CartProvider } from "@/context/CartContext"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })
const syne = Syne({ subsets: ["latin"], variable: "--font-syne" })

export const metadata: Metadata = {
  title: "FakeSH 🛒",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${syne.variable}`}>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
